// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MvcDocument.Models;

namespace MvcDocument.Migrations
{
    [DbContext(typeof(MvcDocumentContext))]
    [Migration("20190520183246_Migration_1")]
    partial class Migration_1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MvcDocument.Models.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount");

                    b.Property<string>("Description");

                    b.HasKey("Id");

                    b.ToTable("Document");
                });

            modelBuilder.Entity("MvcDocument.Models.DocumentStatus", b =>
                {
                    b.Property<int>("DocumentStatusId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateTime");

                    b.Property<int?>("DocumentIdId");

                    b.Property<int>("StatusId");

                    b.HasKey("DocumentStatusId");

                    b.HasIndex("DocumentIdId");

                    b.ToTable("DocumentStatus");
                });

            modelBuilder.Entity("MvcDocument.Models.DocumentStatus", b =>
                {
                    b.HasOne("MvcDocument.Models.Document", "DocumentId")
                        .WithMany()
                        .HasForeignKey("DocumentIdId");
                });
#pragma warning restore 612, 618
        }
    }
}
